using System;
using System.Reflection;
using System.Runtime.InteropServices;

// Only attributes the .NET SDK does NOT generate belong in this file.
//
// Title, Description, Company, Product, Copyright, and all three version attributes are now
// generated by MSBuild from properties in Genie4.csproj and Directory.Build.props, so that CI
// can inject the release version from the git tag. See docs/VERSIONING.md.
//
// Do not re-add [assembly: AssemblyTitle/Description/Company/Product/Copyright/Version/
// FileVersion/InformationalVersion] here -- they would collide with the generated attributes
// and the build would fail with CS0579 "duplicate attribute".

[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("5504d721-dce1-47d4-9182-67aff589cbbb")]
